spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project
    username: root
    password: green502


mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html


logging:
  level:
    "[team6.project.todo.TodoServiceV1]": DEBUG
    "[team6.project.emotion.EmotionMapper]": DEBUG
    "[team6.project.sub.emotionhyunmin.HyunEmotionService]": DEBUG
    "[team6.project.todo.TodoRepository]": DEBUG

server:
  port: 8088


